[env]
# Test with chomp=true - should remove trailing newlines
CONTENT_CHOMPED = "{{ read_file(path='newline_test.txt', chomp=true) }}"
# Test with chomp=false - should preserve trailing newlines (same as default)
CONTENT_NOT_CHOMPED = "{{ read_file(path='newline_test.txt', chomp=false) }}"
# Test default behavior - should preserve trailing newlines
CONTENT_DEFAULT = "{{ read_file(path='newline_test.txt') }}"
